"""Edge -> cloud sync: pushes live rows from the local SQLite database to Supabase.

Why not write to Supabase directly? The backend is the edge device in the cab. Alerts must
never wait on the network, and site Wi-Fi drops. So every write goes to local SQLite first
(fast, always available), and this loop copies new or changed rows to Supabase in the
background. If the network is down, rows stay unsynced and go on the next successful run.

How:
  * every table with the Synced mixin (app/db/models.py) is pushed;
  * a row is due when synced_at IS NULL (new, or edited since its last push -- see
    app/db/tracking.py); seeded history is pre-stamped and never uploaded;
  * rows are upserted into the Supabase table of the same name on `uid`, so a retry after a
    half-failed push is harmless;
  * every row carries `device_id` (which edge box sent it) and `local_id` (its SQLite id).

The Supabase tables are created once with backend/supabase/schema.sql (generated by
`python -m app.sync.supabase --schema`, so it always matches the models).

Config (environment variables, or backend/.env locally):
  SUPABASE_URL, SUPABASE_SECRET_KEY   required; sync stays off without them
  SYNC_ENABLED                        default true when both are set; "false" turns it off
  DEVICE_ID                           default "edge-01"
  SYNC_INTERVAL_S                     default 60
  SYNC_BATCH_SIZE                     default 200
"""
from __future__ import annotations

import asyncio
import logging
import os
from datetime import datetime, timezone

import httpx
from sqlalchemy import Boolean, DateTime, Float, Integer, JSON, String

from app.db.models import Base, Synced, _uid
from app.db.session import SessionLocal

log = logging.getLogger("ironsense.sync")

SKIP_COLUMNS = {"id", "synced_at"}          # local-only; the cloud gets local_id / its own synced time


def _env_bool(name: str, default: bool) -> bool:
    v = os.getenv(name)
    return default if v is None or v.strip() == "" else v.strip().lower() in ("1", "true", "yes", "on")


class SupabaseSync:
    def __init__(self):
        self.url = (os.getenv("SUPABASE_URL") or "").rstrip("/")
        self.key = os.getenv("SUPABASE_SECRET_KEY") or ""
        self.enabled = bool(self.url and self.key) and _env_bool("SYNC_ENABLED", True)
        self.device_id = os.getenv("DEVICE_ID") or "edge-01"
        self.interval = float(os.getenv("SYNC_INTERVAL_S") or 60)
        self.batch = int(os.getenv("SYNC_BATCH_SIZE") or 200)
        self.models = [m.class_ for m in Base.registry.mappers if issubclass(m.class_, Synced)]
        self.last_run: dict = {"at": None, "pushed": {}, "error": None}
        self._task: asyncio.Task | None = None

    # ------------------------------------------------------------------ rows
    def _row(self, obj) -> dict:
        out = {"device_id": self.device_id, "local_id": obj.id}
        for col in obj.__table__.columns:
            if col.name in SKIP_COLUMNS:
                continue
            v = getattr(obj, col.name)
            out[col.name] = v.isoformat() if isinstance(v, datetime) else v
        return out

    def _due(self, model) -> list:
        db = SessionLocal()
        try:
            rows = (db.query(model).filter(model.synced_at.is_(None))
                    .order_by(model.id).limit(self.batch).all())
            for r in rows:
                if r.uid is None:              # rows written before the uid column existed
                    r.uid = _uid()
            db.commit()
            return [(r.id, self._row(r)) for r in rows if r.uid]
        finally:
            db.close()

    def _mark(self, model, ids: list[int], payloads: dict[int, dict]) -> None:
        """Stamp rows as synced, unless they changed again while the push was in flight."""
        now = datetime.now(timezone.utc).replace(tzinfo=None)
        db = SessionLocal()
        try:
            for obj in db.query(model).filter(model.id.in_(ids)).all():
                if obj.synced_at is None and self._row(obj) == payloads[obj.id]:
                    obj.synced_at = now
            db.commit()
        finally:
            db.close()

    # ------------------------------------------------------------------ push
    async def sync_once(self, client: httpx.AsyncClient | None = None) -> dict:
        pushed: dict[str, int] = {}
        own = client is None
        client = client or httpx.AsyncClient(timeout=20)
        try:
            for model in self.models:
                table = model.__tablename__
                while True:
                    due = await asyncio.to_thread(self._due, model)
                    if not due:
                        break
                    r = await client.post(
                        f"{self.url}/rest/v1/{table}", params={"on_conflict": "uid"},
                        json=[row for _, row in due],
                        headers={"apikey": self.key, "Authorization": f"Bearer {self.key}",
                                 "Content-Type": "application/json",
                                 "Prefer": "resolution=merge-duplicates,return=minimal"})
                    if r.status_code >= 300:
                        raise RuntimeError(f"{table}: HTTP {r.status_code} {r.text[:300]}")
                    await asyncio.to_thread(self._mark, model, [i for i, _ in due], dict(due))
                    pushed[table] = pushed.get(table, 0) + len(due)
                    if len(due) < self.batch:
                        break
            self.last_run = {"at": datetime.now(timezone.utc).isoformat(), "pushed": pushed, "error": None}
        except Exception as e:                  # network down, Supabase error: retry next round
            self.last_run = {"at": datetime.now(timezone.utc).isoformat(), "pushed": pushed, "error": str(e)}
            log.warning("supabase sync failed: %s", e)
        finally:
            if own:
                await client.aclose()
        return self.last_run

    async def run(self) -> None:
        async with httpx.AsyncClient(timeout=20) as client:
            while True:
                await asyncio.sleep(self.interval)
                await self.sync_once(client)

    def start(self) -> None:
        if self.enabled:
            log.info("supabase sync on: every %.0fs as %s", self.interval, self.device_id)
            self._task = asyncio.create_task(self.run())
        else:
            log.info("supabase sync off (SUPABASE_URL / SUPABASE_SECRET_KEY missing or SYNC_ENABLED=false)")

    async def stop(self) -> None:
        """Last push on shutdown, so a Render sleep/redeploy loses as little as possible."""
        if self._task:
            self._task.cancel()
            try:
                await asyncio.wait_for(self.sync_once(), timeout=15)
            except Exception:
                pass

    def status(self) -> dict:
        return {"enabled": self.enabled, "device_id": self.device_id, "interval_s": self.interval,
                "last_run": self.last_run}


# ---------------------------------------------------------------------- schema
_PG_TYPES = {Integer: "bigint", Float: "double precision", String: "text", Boolean: "boolean",
             DateTime: "timestamp", JSON: "jsonb"}


def schema_sql() -> str:
    """CREATE TABLE statements for Supabase that mirror the Synced models exactly."""
    out = ["-- Generated by `python -m app.sync.supabase --schema`. Run once in Supabase: SQL Editor -> New query.",
           "-- Safe to re-run: tables and columns are only added, never dropped.", ""]
    for m in [m.class_ for m in Base.registry.mappers if issubclass(m.class_, Synced)]:
        t = m.__table__
        out.append(f"create table if not exists public.{t.name} (")
        out.append("  uid text primary key,")
        out.append("  device_id text not null,")
        out.append("  local_id bigint,")
        cols = [c for c in t.columns if c.name not in SKIP_COLUMNS | {"uid"}]
        for c in cols:
            pg = next((v for k, v in _PG_TYPES.items() if isinstance(c.type, k)), "text")
            out.append(f"  {c.name} {pg},")
        out.append("  cloud_received_at timestamptz not null default now()")
        out.append(");")
        for c in cols:   # lets a re-run pick up columns added after the first run
            pg = next((v for k, v in _PG_TYPES.items() if isinstance(c.type, k)), "text")
            out.append(f"alter table public.{t.name} add column if not exists {c.name} {pg};")
        for c in ("device_id", "session_id", "machine_id", "operator_id", "timestamp"):
            if c == "device_id" or c in t.columns:
                out.append(f"create index if not exists {t.name}_{c}_idx on public.{t.name} ({c});")
        # Only the backend's secret key (which bypasses RLS) may read or write.
        out.append(f"alter table public.{t.name} enable row level security;")
        out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    import sys

    if "--schema" in sys.argv:
        print(schema_sql())
    else:
        from app.config import load_env
        from app.db.session import init_db

        load_env()
        init_db()
        s = SupabaseSync()
        print("enabled:", s.enabled, "device:", s.device_id)
        print(asyncio.run(s.sync_once()) if s.enabled else "set SUPABASE_URL and SUPABASE_SECRET_KEY first")
