-- Generated by `python -m app.sync.supabase --schema`. Run once in Supabase: SQL Editor -> New query.
-- Safe to re-run: tables and columns are only added, never dropped.

create table if not exists public.task_records (
  uid text primary key,
  device_id text not null,
  local_id bigint,
  task_id text,
  machine_id text,
  operator_id text,
  task_type text,
  planned_min double precision,
  actual_min double precision,
  predicted_p50_min double precision,
  started_at timestamp,
  completed_at timestamp,
  session_id text,
  cloud_received_at timestamptz not null default now()
);
alter table public.task_records add column if not exists task_id text;
alter table public.task_records add column if not exists machine_id text;
alter table public.task_records add column if not exists operator_id text;
alter table public.task_records add column if not exists task_type text;
alter table public.task_records add column if not exists planned_min double precision;
alter table public.task_records add column if not exists actual_min double precision;
alter table public.task_records add column if not exists predicted_p50_min double precision;
alter table public.task_records add column if not exists started_at timestamp;
alter table public.task_records add column if not exists completed_at timestamp;
alter table public.task_records add column if not exists session_id text;
create index if not exists task_records_device_id_idx on public.task_records (device_id);
create index if not exists task_records_session_id_idx on public.task_records (session_id);
create index if not exists task_records_machine_id_idx on public.task_records (machine_id);
create index if not exists task_records_operator_id_idx on public.task_records (operator_id);
alter table public.task_records enable row level security;

create table if not exists public.alerts (
  uid text primary key,
  device_id text not null,
  local_id bigint,
  alert_id text,
  machine_id text,
  operator_id text,
  alert_type text,
  severity text,
  message text,
  timestamp timestamp,
  acknowledged boolean,
  session_id text,
  cloud_received_at timestamptz not null default now()
);
alter table public.alerts add column if not exists alert_id text;
alter table public.alerts add column if not exists machine_id text;
alter table public.alerts add column if not exists operator_id text;
alter table public.alerts add column if not exists alert_type text;
alter table public.alerts add column if not exists severity text;
alter table public.alerts add column if not exists message text;
alter table public.alerts add column if not exists timestamp timestamp;
alter table public.alerts add column if not exists acknowledged boolean;
alter table public.alerts add column if not exists session_id text;
create index if not exists alerts_device_id_idx on public.alerts (device_id);
create index if not exists alerts_session_id_idx on public.alerts (session_id);
create index if not exists alerts_machine_id_idx on public.alerts (machine_id);
create index if not exists alerts_operator_id_idx on public.alerts (operator_id);
create index if not exists alerts_timestamp_idx on public.alerts (timestamp);
alter table public.alerts enable row level security;

create table if not exists public.training_completions (
  uid text primary key,
  device_id text not null,
  local_id bigint,
  operator_id text,
  module_id text,
  completed_at timestamp,
  quiz_score double precision,
  cloud_received_at timestamptz not null default now()
);
alter table public.training_completions add column if not exists operator_id text;
alter table public.training_completions add column if not exists module_id text;
alter table public.training_completions add column if not exists completed_at timestamp;
alter table public.training_completions add column if not exists quiz_score double precision;
create index if not exists training_completions_device_id_idx on public.training_completions (device_id);
create index if not exists training_completions_operator_id_idx on public.training_completions (operator_id);
alter table public.training_completions enable row level security;

create table if not exists public.hourly_summaries (
  uid text primary key,
  device_id text not null,
  local_id bigint,
  machine_id text,
  operator_id text,
  timestamp timestamp,
  engine_hours double precision,
  fuel_used_l double precision,
  load_cycles bigint,
  idling_time_min double precision,
  engine_on_min double precision,
  seatbelt_status text,
  seatbelt_compliance_pct double precision,
  safety_alert_triggered text,
  safety_alerts bigint,
  fuel_per_cycle_l double precision,
  session_id text,
  cloud_received_at timestamptz not null default now()
);
alter table public.hourly_summaries add column if not exists machine_id text;
alter table public.hourly_summaries add column if not exists operator_id text;
alter table public.hourly_summaries add column if not exists timestamp timestamp;
alter table public.hourly_summaries add column if not exists engine_hours double precision;
alter table public.hourly_summaries add column if not exists fuel_used_l double precision;
alter table public.hourly_summaries add column if not exists load_cycles bigint;
alter table public.hourly_summaries add column if not exists idling_time_min double precision;
alter table public.hourly_summaries add column if not exists engine_on_min double precision;
alter table public.hourly_summaries add column if not exists seatbelt_status text;
alter table public.hourly_summaries add column if not exists seatbelt_compliance_pct double precision;
alter table public.hourly_summaries add column if not exists safety_alert_triggered text;
alter table public.hourly_summaries add column if not exists safety_alerts bigint;
alter table public.hourly_summaries add column if not exists fuel_per_cycle_l double precision;
alter table public.hourly_summaries add column if not exists session_id text;
create index if not exists hourly_summaries_device_id_idx on public.hourly_summaries (device_id);
create index if not exists hourly_summaries_session_id_idx on public.hourly_summaries (session_id);
create index if not exists hourly_summaries_machine_id_idx on public.hourly_summaries (machine_id);
create index if not exists hourly_summaries_operator_id_idx on public.hourly_summaries (operator_id);
create index if not exists hourly_summaries_timestamp_idx on public.hourly_summaries (timestamp);
alter table public.hourly_summaries enable row level security;

create table if not exists public.anomaly_events (
  uid text primary key,
  device_id text not null,
  local_id bigint,
  machine_id text,
  operator_id text,
  anomaly_type text,
  method text,
  score double precision,
  explanation jsonb,
  timestamp timestamp,
  session_id text,
  cloud_received_at timestamptz not null default now()
);
alter table public.anomaly_events add column if not exists machine_id text;
alter table public.anomaly_events add column if not exists operator_id text;
alter table public.anomaly_events add column if not exists anomaly_type text;
alter table public.anomaly_events add column if not exists method text;
alter table public.anomaly_events add column if not exists score double precision;
alter table public.anomaly_events add column if not exists explanation jsonb;
alter table public.anomaly_events add column if not exists timestamp timestamp;
alter table public.anomaly_events add column if not exists session_id text;
create index if not exists anomaly_events_device_id_idx on public.anomaly_events (device_id);
create index if not exists anomaly_events_session_id_idx on public.anomaly_events (session_id);
create index if not exists anomaly_events_machine_id_idx on public.anomaly_events (machine_id);
create index if not exists anomaly_events_operator_id_idx on public.anomaly_events (operator_id);
create index if not exists anomaly_events_timestamp_idx on public.anomaly_events (timestamp);
alter table public.anomaly_events enable row level security;

create table if not exists public.instructor_bookings (
  uid text primary key,
  device_id text not null,
  local_id bigint,
  operator_id text,
  module_id text,
  preferred_slot timestamp,
  confirmed_slot timestamp,
  status text,
  created_at timestamp,
  cloud_received_at timestamptz not null default now()
);
alter table public.instructor_bookings add column if not exists operator_id text;
alter table public.instructor_bookings add column if not exists module_id text;
alter table public.instructor_bookings add column if not exists preferred_slot timestamp;
alter table public.instructor_bookings add column if not exists confirmed_slot timestamp;
alter table public.instructor_bookings add column if not exists status text;
alter table public.instructor_bookings add column if not exists created_at timestamp;
create index if not exists instructor_bookings_device_id_idx on public.instructor_bookings (device_id);
create index if not exists instructor_bookings_operator_id_idx on public.instructor_bookings (operator_id);
alter table public.instructor_bookings enable row level security;

create table if not exists public.shift_sessions (
  uid text primary key,
  device_id text not null,
  local_id bigint,
  session_id text,
  machine_id text,
  operator_id text,
  scenario_id text,
  seed bigint,
  time_scale double precision,
  started_at timestamp,
  last_seen_at timestamp,
  wall_started_at timestamp,
  wall_last_seen_at timestamp,
  cloud_received_at timestamptz not null default now()
);
alter table public.shift_sessions add column if not exists session_id text;
alter table public.shift_sessions add column if not exists machine_id text;
alter table public.shift_sessions add column if not exists operator_id text;
alter table public.shift_sessions add column if not exists scenario_id text;
alter table public.shift_sessions add column if not exists seed bigint;
alter table public.shift_sessions add column if not exists time_scale double precision;
alter table public.shift_sessions add column if not exists started_at timestamp;
alter table public.shift_sessions add column if not exists last_seen_at timestamp;
alter table public.shift_sessions add column if not exists wall_started_at timestamp;
alter table public.shift_sessions add column if not exists wall_last_seen_at timestamp;
create index if not exists shift_sessions_device_id_idx on public.shift_sessions (device_id);
create index if not exists shift_sessions_session_id_idx on public.shift_sessions (session_id);
create index if not exists shift_sessions_machine_id_idx on public.shift_sessions (machine_id);
create index if not exists shift_sessions_operator_id_idx on public.shift_sessions (operator_id);
alter table public.shift_sessions enable row level security;

create table if not exists public.readiness_snapshots (
  uid text primary key,
  device_id text not null,
  local_id bigint,
  machine_id text,
  timestamp timestamp,
  readiness_score bigint,
  readiness_breakdown jsonb,
  session_id text,
  cloud_received_at timestamptz not null default now()
);
alter table public.readiness_snapshots add column if not exists machine_id text;
alter table public.readiness_snapshots add column if not exists timestamp timestamp;
alter table public.readiness_snapshots add column if not exists readiness_score bigint;
alter table public.readiness_snapshots add column if not exists readiness_breakdown jsonb;
alter table public.readiness_snapshots add column if not exists session_id text;
create index if not exists readiness_snapshots_device_id_idx on public.readiness_snapshots (device_id);
create index if not exists readiness_snapshots_session_id_idx on public.readiness_snapshots (session_id);
create index if not exists readiness_snapshots_machine_id_idx on public.readiness_snapshots (machine_id);
create index if not exists readiness_snapshots_timestamp_idx on public.readiness_snapshots (timestamp);
alter table public.readiness_snapshots enable row level security;

create table if not exists public.incidents (
  uid text primary key,
  device_id text not null,
  local_id bigint,
  machine_id text,
  operator_id text,
  incident_type text,
  severity text,
  cause text,
  source text,
  timestamp timestamp,
  telemetry_window jsonb,
  session_id text,
  cloud_received_at timestamptz not null default now()
);
alter table public.incidents add column if not exists machine_id text;
alter table public.incidents add column if not exists operator_id text;
alter table public.incidents add column if not exists incident_type text;
alter table public.incidents add column if not exists severity text;
alter table public.incidents add column if not exists cause text;
alter table public.incidents add column if not exists source text;
alter table public.incidents add column if not exists timestamp timestamp;
alter table public.incidents add column if not exists telemetry_window jsonb;
alter table public.incidents add column if not exists session_id text;
create index if not exists incidents_device_id_idx on public.incidents (device_id);
create index if not exists incidents_session_id_idx on public.incidents (session_id);
create index if not exists incidents_machine_id_idx on public.incidents (machine_id);
create index if not exists incidents_operator_id_idx on public.incidents (operator_id);
create index if not exists incidents_timestamp_idx on public.incidents (timestamp);
alter table public.incidents enable row level security;

